version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Flask configuration
      - FLASK_APP=app.py
      - FLASK_ENV=production
      # Cloud Redis connection details from .env
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # GROQ API key for essay feedback
      - GROQ_API_KEY=${GROQ_API_KEY}