services:
  - type: web
    name: essay-feedback-app
    env: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        value: your_groq_api_key_here
      - key: SECRET_KEY
        generateValue: true
