services:
  - type: web
    name: essay-feedback-app
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false  # Set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_HOST
        sync: false  # Set in Render dashboard or link to Redis instance
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false